// SPDX-License-Identifier: 0BSD
// Port of OpenAI tiktoken CoreBPE + byte_pair_encode (src/lib.rs).
#include "cl100k.hpp"

#include <algorithm>
#include <cstdint>
#include <cstring>
#include <limits>
#include <queue>
#include <unordered_map>
#include <vector>
#include <zlib.h>

#define PCRE2_CODE_UNIT_WIDTH 8
#include <pcre2.h>

// Generated by CMake from data/cl100k_vocab.z (xxd -i).
#include "cl100k_vocab.inc"

namespace tokenc {
namespace {

constexpr Rank kRankMax = std::numeric_limits<Rank>::max();

// tiktoken_ext/openai_public.py — cl100k_base()
constexpr const char* kCl100kPattern =
    "'(?i:[sdmt]|ll|ve|re)|[^\\r\\n\\p{L}\\p{N}]?+\\p{L}++|\\p{N}{1,3}+| ?[^\\s\\p{L}\\p{N}]++[\\r\\n]*+|\\s++$|\\s*[\\r\\n]|\\s+(?!\\S)|\\s";

struct StringHash {
    using is_transparent = void;
    std::size_t operator()(std::string_view s) const noexcept
    {
        return std::hash<std::string_view>{}(s);
    }
};

struct RankHash {
    std::size_t operator()(const std::vector<std::uint8_t>& k) const noexcept
    {
        std::size_t h = 0;
        for (auto b : k)
            h = h * 131 + b;
        return h;
    }
};

using EncoderMap = std::unordered_map<std::vector<std::uint8_t>, Rank, RankHash>;

struct Merge {
    std::size_t start = 0;
    Rank rank = kRankMax;
};

struct MergeCmp {
    bool operator()(const Merge& a, const Merge& b) const
    {
        if (a.rank != b.rank)
            return a.rank > b.rank;
        return a.start > b.start;
    }
};

struct State {
    std::size_t prev = 0;
    std::size_t end = 0;
    std::size_t next_end = 0;
    Rank next_rank = kRankMax;
    Rank cur_rank = kRankMax;
};

Rank map_lookup(const EncoderMap& enc, std::string_view key)
{
    std::vector<std::uint8_t> k(key.begin(), key.end());
    const auto it = enc.find(k);
    return it == enc.end() ? kRankMax : it->second;
}

std::vector<Rank> byte_pair_merge_small(const EncoderMap& enc, std::string_view piece)
{
    const std::size_t piece_len = piece.size();

    std::vector<std::pair<std::size_t, Rank>> parts;
    parts.reserve(piece_len + 1);

    std::pair<Rank, std::size_t> min_rank{kRankMax, piece_len};
    for (std::size_t i = 0; i + 1 < piece_len; ++i) {
        const Rank rank = map_lookup(enc, piece.substr(i, 2));
        if (rank < min_rank.first)
            min_rank = {rank, i};
        parts.emplace_back(i, rank);
    }
    parts.emplace_back(piece_len - 1, kRankMax);
    parts.emplace_back(piece_len, kRankMax);

    auto get_rank = [&](std::size_t i) -> Rank {
        if (i + 3 < parts.size())
            return map_lookup(enc, piece.substr(parts[i].first, parts[i + 3].first - parts[i].first));
        return kRankMax;
    };

    while (min_rank.first != kRankMax) {
        const std::size_t i = min_rank.second;
        if (i > 0)
            parts[i - 1].second = get_rank(i - 1);
        parts[i].second = get_rank(i);
        parts.erase(parts.begin() + static_cast<std::ptrdiff_t>(i + 1));

        min_rank = {kRankMax, piece_len};
        for (std::size_t j = 0; j + 1 < parts.size(); ++j) {
            if (parts[j].second < min_rank.first)
                min_rank = {parts[j].second, j};
        }
    }

    std::vector<Rank> out;
    out.reserve(parts.size());
    for (std::size_t w = 0; w + 1 < parts.size(); ++w)
        out.push_back(map_lookup(enc, piece.substr(parts[w].first, parts[w + 1].first - parts[w].first)));
    return out;
}

std::vector<Rank> byte_pair_merge_large(const EncoderMap& enc, std::string_view piece)
{
    const std::size_t piece_len = piece.size();

    std::vector<State> state;
    state.reserve(piece_len);
    state.push_back({std::numeric_limits<std::size_t>::max(), 1, 2, kRankMax, kRankMax});

    std::priority_queue<Merge, std::vector<Merge>, MergeCmp> heap;
    for (std::size_t i = 0; i + 1 < piece_len; ++i) {
        const Rank rank = map_lookup(enc, piece.substr(i, 2));
        if (rank != kRankMax)
            heap.push({i, rank});
        state.push_back({i, i + 2, i + 3, kRankMax, kRankMax});
        if (rank != kRankMax)
            state[i].next_rank = rank;
    }

    auto potential_merge = [&](std::size_t start, std::size_t next_end_item) {
        state[start].next_end = next_end_item;
        state[start].next_rank = kRankMax;
        if (next_end_item <= piece_len) {
            const Rank rank = map_lookup(enc, piece.substr(start, next_end_item - start));
            if (rank != kRankMax) {
                heap.push({start, rank});
                state[start].next_rank = rank;
            }
        }
    };

    while (!heap.empty()) {
        Merge left = heap.top();
        heap.pop();
        if (left.rank == kRankMax)
            break;
        if (left.rank != state[left.start].next_rank)
            continue;

        const std::size_t left_start = left.start;
        const std::size_t right_start = state[left_start].end;
        const std::size_t right_end = state[left_start].next_end;
        const std::size_t right_next_end = state[right_start].next_end;

        state[left_start].cur_rank = state[left_start].next_rank;
        state[left_start].end = right_end;
        potential_merge(left_start, right_next_end);
        if (right_end < state.size())
            state[right_end].prev = left_start;
        if (left_start > 0) {
            const std::size_t prev_start = state[left_start].prev;
            potential_merge(prev_start, right_end);
        }
        state[right_start].next_rank = kRankMax;
    }

    std::vector<Rank> result;
    for (std::size_t i = 0; i < state.size();) {
        if (state[i].cur_rank != kRankMax)
            result.push_back(state[i].cur_rank);
        else
            result.push_back(map_lookup(enc, piece.substr(i, state[i].end - i)));
        i = state[i].end;
    }
    return result;
}

std::vector<Rank> byte_pair_encode(std::string_view piece, const EncoderMap& enc)
{
    if (piece.empty())
        return {};
    if (piece.size() == 1)
        return {map_lookup(enc, piece)};
    if (piece.size() < 100)
        return byte_pair_merge_small(enc, piece);
    return byte_pair_merge_large(enc, piece);
}

bool load_vocab(EncoderMap& enc, std::vector<std::string>& token_bytes, std::vector<Rank>& token_ranks)
{
    enc.clear();
    token_bytes.clear();
    token_ranks.clear();

    uLongf dst_len = cl100k_vocab_z_len * 4;
    std::vector<std::uint8_t> buf(dst_len);
    const int zr = uncompress(buf.data(), &dst_len, cl100k_vocab_z, cl100k_vocab_z_len);
    if (zr != Z_OK)
        return false;

    const std::uint8_t* p = buf.data();
    const std::uint8_t* end = p + dst_len;
    if (end - p < 4)
        return false;
    std::uint32_t n = 0;
    std::memcpy(&n, p, 4);
    p += 4;

    token_bytes.resize(n);
    token_ranks.resize(n);
    for (std::uint32_t i = 0; i < n; ++i) {
        if (end - p < 2)
            return false;
        std::uint16_t len = 0;
        std::memcpy(&len, p, 2);
        p += 2;
        if (end - p < len)
            return false;
        token_bytes[i].assign(reinterpret_cast<const char*>(p), len);
        p += len;
        token_ranks[i] = i;
        enc.emplace(std::vector<std::uint8_t>(token_bytes[i].begin(), token_bytes[i].end()), i);
    }
    return p == end;
}

struct RegexHolder {
    pcre2_code* re = nullptr;
    pcre2_match_data* md = nullptr;

    RegexHolder()
    {
        int err = 0;
        PCRE2_SIZE erroff = 0;
        re = pcre2_compile(reinterpret_cast<PCRE2_SPTR>(kCl100kPattern),
                           PCRE2_ZERO_TERMINATED,
                           PCRE2_UTF | PCRE2_UCP,
                           &err,
                           &erroff,
                           nullptr);
        if (!re)
            return;
        md = pcre2_match_data_create_from_pattern(re, nullptr);
    }

    ~RegexHolder()
    {
        if (md)
            pcre2_match_data_free(md);
        if (re)
            pcre2_code_free(re);
    }
};

const EncoderMap& encoder_map()
{
    static EncoderMap enc;
    static std::vector<std::string> token_bytes;
    static std::vector<Rank> token_ranks;
    static bool ok = load_vocab(enc, token_bytes, token_ranks);
    (void)ok;
    return enc;
}

const RegexHolder& regex_holder()
{
    static RegexHolder holder;
    return holder;
}

}  // namespace

Cl100kEncoder::Cl100kEncoder() = default;

const Cl100kEncoder& Cl100kEncoder::instance()
{
    static Cl100kEncoder enc;
    return enc;
}

Rank Cl100kEncoder::lookup(std::string_view key) const
{
    return map_lookup(encoder_map(), key);
}

std::vector<Rank> Cl100kEncoder::byte_pair_encode(std::string_view piece) const
{
    return tokenc::byte_pair_encode(piece, encoder_map());
}

std::vector<Rank> Cl100kEncoder::encode_ordinary(std::string_view text) const
{
    const auto& rx = regex_holder();
    std::vector<Rank> out;
    if (!rx.re || !rx.md)
        return out;

    PCRE2_SIZE start = 0;
    const PCRE2_SIZE subject_len = text.size();
    const auto* subject = reinterpret_cast<PCRE2_SPTR>(text.data());

    while (start <= subject_len) {
        const int rc = pcre2_match(rx.re,
                                   subject,
                                   subject_len,
                                   start,
                                   0,
                                   rx.md,
                                   nullptr);
        if (rc < 0) {
            if (rc == PCRE2_ERROR_NOMATCH)
                break;
            break;
        }

        PCRE2_SIZE* ovector = pcre2_get_ovector_pointer(rx.md);
        const PCRE2_SIZE o0 = ovector[0];
        const PCRE2_SIZE o1 = ovector[1];
        const std::string_view piece(text.data() + o0, o1 - o0);
        const Rank whole = lookup(piece);
        if (whole != kRankMax)
            out.push_back(whole);
        else {
            const auto tokens = byte_pair_encode(piece);
            out.insert(out.end(), tokens.begin(), tokens.end());
        }
        start = o1;
    }
    return out;
}

std::size_t Cl100kEncoder::count_tokens(std::string_view text) const
{
    return encode_ordinary(text).size();
}

}  // namespace tokenc