// SPDX-License-Identifier: 0BSD
#include "counter.hpp"

#include <fcntl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>

#include <algorithm>
#include <atomic>
#include <cstdio>
#include <cstring>
#include <thread>

#include "cache.hpp"
#include "tokenize.hpp"

// How many leading bytes of a file to scan for a generator banner. Generators
// put the banner at the very top, so 1 KiB is comfortably enough. File-scope
// constant so both the anonymous-namespace helper and the external
// is_generated_file() below can see it.
static constexpr std::size_t kGenScanBytes = 1024;

namespace tokenc {
namespace {

// Count '\n' in [data, data+n). A trailing non-empty fragment without '\n'
// counts as one more line (matching `wc -l` for the newlines + 1 for missing
// final newline when the file has content but no trailing newline).
std::uint64_t count_newlines(const char* data, std::size_t n)
{
    if (n == 0)
        return 0;
    std::uint64_t nl = 0;
    const char* p = data;
    const char* end = data + n;
    // memchr is vectorized and much faster than a per-byte loop on big files.
    while (p < end) {
        const void* hit = std::memchr(p, '\n', static_cast<std::size_t>(end - p));
        if (!hit)
            break;
        ++nl;
        p = static_cast<const char*>(hit) + 1;
    }
    if (end[-1] != '\n')
        ++nl;  // a final line with no terminating newline
    return nl;
}

// Standard generator banners. We look for the exact phrases that code
// generators emit verbatim at the very top of a file, and only within the first
// few lines — this avoids false positives where a hand-written file happens to
// contain words like "do not edit" or "generated by" deeper in the body.
//
// Covers: protoc / protoc-gen-go / protoc-gen-grpc (C++, Go, Python, Java,
// Ruby, JS, ...), Thrift, mockgen, stringer, Wire, protobuf-es, Bazel
// (@generated), openapi-generator, and the Google style-guide convention.
bool header_has_generated_marker(const char* data, std::size_t n)
{
    // Restrict the scan to the first few lines of the file. Generators put the
    // banner at the top; real source rarely has these exact phrases there.
    const std::size_t kMaxLines = 6;
    std::size_t limit = n;
    std::size_t nl_count = 0;
    for (std::size_t i = 0; i < n; ++i) {
        if (data[i] == '\n') {
            ++nl_count;
            if (nl_count == kMaxLines) { limit = i; break; }
        }
    }

    auto contains = [&](std::string_view needle) -> bool {
        if (needle.size() > limit) return false;
        for (std::size_t i = 0; i + needle.size() <= limit; ++i) {
            bool ok = true;
            for (std::size_t j = 0; j < needle.size(); ++j) {
                char a = data[i + j];
                if (a >= 'A' && a <= 'Z') a = static_cast<char>(a - 'A' + 'a');
                char b = needle[j];
                if (b >= 'A' && b <= 'Z') b = static_cast<char>(b - 'A' + 'a');
                if (a != b) { ok = false; break; }
            }
            if (ok) return true;
        }
        return false;
    };

    // Canonical, generator-specific phrases only (no bare "do not edit"). The
    // concrete generator names make this safe against hand-written code that
    // merely happens to say "do not edit" or "generated by" somewhere.
    if (contains("code generated")) return true;                    // protoc-gen-go, mockgen, stringer, wire
    if (contains("generated by the protocol buffer compiler")) return true;  // protoc C++/Python/Java/Ruby/JS
    if (contains("protoc-gen-")) return true;                       // any protoc plugin
    if (contains("autogenerated by thrift")) return true;           // Apache Thrift
    if (contains("automatically generated by apollo")) return true; // apollo graphql
    if (contains("generated by the gRPC")) return true;             // gRPC stubs
    if (contains("generated by the jsonpb")) return true;
    if (contains("automatically generated by ")) return true;       // generic banner header
    if (contains("@generated")) return true;                        // protobuf-es / Bazel / starlark
    return false;
}

}  // namespace

// Canonical protoc / protoc-gen-* output filenames. These are unambiguous and
// never hand-written, so matching by basename is reliable AND keeps the files
// reachable via --include-generated (unlike putting them in default-ignore).
// Returns true if the basename of `path` ends with one of these suffixes.
bool filename_is_generated(const std::string& path)
{
    // Extract basename.
    std::size_t base = path.find_last_of("/\\");
    std::string name = (base == std::string::npos) ? path : path.substr(base + 1);

    auto ends_with = [&](std::string_view suf) {
        return name.size() >= suf.size() &&
               name.compare(name.size() - suf.size(), suf.size(), suf) == 0;
    };
    // protoc-gen-go / protoc-gen-go-grpc
    if (ends_with(".pb.go")) return true;
    if (ends_with("_grpc.pb.go")) return true;
    // protoc C / C++ / Objective-C
    if (ends_with(".pb.cc")) return true;
    if (ends_with(".pb.cpp")) return true;
    if (ends_with(".pb.c")) return true;
    if (ends_with(".pb.h")) return true;
    if (ends_with(".pb.m")) return true;
    if (ends_with(".pb.mm")) return true;
    // protoc Python
    if (ends_with("_pb2.py")) return true;
    if (ends_with("_pb2_grpc.py")) return true;
    // protoc Dart
    if (ends_with(".pb.dart")) return true;
    if (ends_with("_pb.dart")) return true;
    if (ends_with("_pb2.dart")) return true;
    return false;
}

bool is_generated_file(const std::string& path)
{
    if (filename_is_generated(path))
        return true;
    const int fd = ::open(path.c_str(), O_RDONLY | O_CLOEXEC);
    if (fd < 0)
        return false;
    char buf[kGenScanBytes];
    const ssize_t got = ::read(fd, buf, sizeof(buf));
    ::close(fd);
    if (got <= 0)
        return false;
    // header_has_generated_marker lives in the anon namespace above; it is
    // reachable here because this function is still in the same translation unit.
    return header_has_generated_marker(buf, static_cast<std::size_t>(got));
}

std::uint64_t count_lines(const std::string& path)
{
    const int fd = ::open(path.c_str(), O_RDONLY | O_CLOEXEC);
    if (fd < 0)
        return 0;
    struct ::stat st;
    if (::fstat(fd, &st) != 0 || !S_ISREG(st.st_mode) || st.st_size == 0) {
        ::close(fd);
        return 0;
    }
    const std::size_t size = static_cast<std::size_t>(st.st_size);

    std::uint64_t lines = 0;
    void* mapped = ::mmap(nullptr, size, PROT_READ, MAP_PRIVATE, fd, 0);
    if (mapped == MAP_FAILED) {
        // Fallback: read in chunks. (Should be rare.)
        std::string buf;
        buf.resize(1 << 16);
        std::size_t total_nl = 0;
        bool any = false;
        bool last_nl = false;
        while (true) {
            const ssize_t r = ::read(fd, buf.data(), buf.size());
            if (r <= 0)
                break;
            any = true;
            const char* p = buf.data();
            const char* e = p + r;
            while (p < e) {
                const void* hit = std::memchr(p, '\n', static_cast<std::size_t>(e - p));
                if (!hit) {
                    last_nl = false;
                    break;
                }
                ++total_nl;
                last_nl = true;
                p = static_cast<const char*>(hit) + 1;
            }
        }
        lines = any ? total_nl + (last_nl ? 0 : 1) : 0;
    } else {
        // Advise the kernel we will read this sequentially.
        ::madvise(mapped, size, MADV_SEQUENTIAL);
        lines = count_newlines(static_cast<const char*>(mapped), size);
        ::munmap(mapped, size);
    }
    ::close(fd);
    return lines;
}

std::vector<LanguageStats> count_all(std::vector<FoundFile>& files,
                                     LineCache* cache,
                                     unsigned threads,
                                     CountTotals& totals,
                                     bool skip_generated,
                                     bool count_tokens)
{
    if (threads == 0) {
        const unsigned hw = std::thread::hardware_concurrency();
        threads = hw > 0 ? hw : 4;
    }
    if (threads > files.size())
        threads = static_cast<unsigned>(files.size());
    if (threads == 0)
        threads = 1;

    const std::size_t n = files.size();
    std::vector<std::uint64_t> counts(n, 0);
    std::vector<std::uint64_t> tok_cl(n, 0);
    std::vector<std::uint64_t> tok_o2(n, 0);
    std::vector<unsigned char> counted(n, 0);        // 1 if line cache hit
    std::vector<unsigned char> tok_cached(n, 0);     // 1 if full token cache hit
    std::vector<unsigned char> tok_done(n, 0);     // 1 if token counts are known
    std::vector<unsigned char> generated(n, 0);      // 1 if excluded as generated

    std::atomic<std::size_t> next{0};
    auto worker = [&]() {
        while (true) {
            const std::size_t i = next.fetch_add(1, std::memory_order_relaxed);
            if (i >= n)
                break;
            // Skip generated files (do NOT count, do NOT cache them as 0 —
            // caching would corrupt the line total for that path).
            if (skip_generated && is_generated_file(files[i].path)) {
                generated[i] = 1;
                continue;
            }
            if (cache && count_tokens) {
                std::uint64_t cl = 0, o2 = 0, cached_lines = 0;
                if (cache->lookup_tokens(files[i].path, files[i].stat, cached_lines, cl, o2)) {
                    counts[i] = cached_lines;
                    tok_cl[i] = cl;
                    tok_o2[i] = o2;
                    counted[i] = 1;
                    tok_cached[i] = 1;
                    tok_done[i] = 1;
                    continue;
                }
            }
            if (cache) {
                std::uint64_t cached = 0;
                if (cache->lookup(files[i].path, files[i].stat, cached)) {
                    counts[i] = cached;
                    counted[i] = 1;
                    if (!count_tokens)
                        continue;
                }
            }
            if (!counted[i])
                counts[i] = count_lines(files[i].path);
        }
    };

    std::vector<std::thread> pool;
    pool.reserve(threads);
    for (unsigned t = 0; t < threads; ++t)
        pool.emplace_back(worker);
    for (auto& th : pool)
        th.join();

    if (count_tokens && tokenizers_available()) {
        std::vector<std::string> todo_paths;
        std::vector<std::size_t> todo_idx;
        todo_paths.reserve(n);
        todo_idx.reserve(n);
        for (std::size_t i = 0; i < n; ++i) {
            if (generated[i] || tok_cached[i])
                continue;
            todo_paths.push_back(files[i].path);
            todo_idx.push_back(i);
        }
        std::unordered_map<std::string, TokenCounts> tok_map;
        if (tokenize_files(todo_paths, tok_map)) {
            for (std::size_t k = 0; k < todo_idx.size(); ++k) {
                const std::size_t i = todo_idx[k];
                if (auto it = tok_map.find(files[i].path); it != tok_map.end()) {
                    tok_cl[i] = it->second.cl100k_base;
                    tok_o2[i] = it->second.o200k_base;
                    tok_done[i] = 1;
                }
            }
        }
    } else if (count_tokens) {
        static bool warned = false;
        if (!warned) {
            std::fprintf(stderr,
                         "tokenc: tokenizers unavailable (need python3 + tiktoken); "
                         "cl100k_base/o200k_base columns will be 0\n");
            warned = true;
        }
    }

    // Aggregate per language. Generated files are dropped entirely.
    std::unordered_map<std::string, LanguageStats> by_lang;
    by_lang.reserve(64);
    totals = {};
    for (std::size_t i = 0; i < n; ++i) {
        if (generated[i])
            continue;
        auto it = by_lang.find(files[i].language);
        if (it == by_lang.end()) {
            LanguageStats ls;
            ls.language = files[i].language;
            auto [ins, _] = by_lang.emplace(files[i].language, std::move(ls));
            it = ins;
        }
        it->second.files += 1;
        it->second.lines += counts[i];
        it->second.cl100k_base += tok_cl[i];
        it->second.o200k_base += tok_o2[i];
        totals.files += 1;
        totals.lines += counts[i];
        totals.cl100k_base += tok_cl[i];
        totals.o200k_base += tok_o2[i];

        if (cache) {
            if (count_tokens && tok_done[i] && !tok_cached[i]) {
                cache->store_tokens(files[i].path, files[i].stat, counts[i],
                                    tok_cl[i], tok_o2[i]);
            } else if (!counted[i]) {
                cache->store(files[i].path, files[i].stat, counts[i]);
            }
        }
    }

    std::vector<LanguageStats> result;
    result.reserve(by_lang.size());
    for (auto& [_, v] : by_lang)
        result.push_back(std::move(v));
    return result;
}

}  // namespace tokenc
