// SPDX-License-Identifier: 0BSD
// Fast physical line counting using mmap and a thread pool.
//
// A "line" is a maximal run of bytes terminated by '\n'. A file that does not
// end with a newline still contributes a line for its trailing content (so a
// single non-empty byte counts as one line, matching `wc -l` for the newline
// count plus one for a missing final newline).
//
// Empty (zero-byte) files contribute zero lines.

#pragma once

#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

#include "walker.hpp"

namespace tokenc {

// Count the physical lines of one file via mmap. Returns 0 for empty or
// unreadable files. The path must be NUL-terminated (use std::string).
std::uint64_t count_lines(const std::string& path);

// Heuristically detect machine-generated source files by scanning the file's
// leading bytes for standard generator banners (e.g. "DO NOT EDIT",
// "Code generated by protoc-gen-go", "Generated by the protocol buffer
// compiler", "@generated"). Reads at most the first few hundred bytes. Returns
// true if the file looks generated and should be excluded from counting.
bool is_generated_file(const std::string& path);

// Per-language aggregate totals.
struct LanguageStats {
    std::string language;
    std::uint64_t files = 0;
    std::uint64_t lines = 0;
    std::uint64_t cl100k_base = 0;
    std::uint64_t o200k_base = 0;
};

// A cache of (dev,ino,mtime,size) -> lines for files we already counted.
// Forward-declared here so the counter can use it without including cache.hpp.
class LineCache;

// Count all files in parallel, optionally consulting/updating `cache`.
// `threads` <= 0 means auto (= hardware concurrency).
// When `skip_generated` is true, files that look machine-generated (see
// is_generated_file) are excluded from the totals and dropped from the result.
struct CountTotals {
    std::uint64_t files = 0;
    std::uint64_t lines = 0;
    std::uint64_t cl100k_base = 0;
    std::uint64_t o200k_base = 0;
};

std::vector<LanguageStats> count_all(std::vector<FoundFile>& files,
                                     LineCache* cache,
                                     unsigned threads,
                                     CountTotals& totals,
                                     bool skip_generated,
                                     bool count_tokens);

}  // namespace tokenc
